apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nginx-tls
  namespace: cert-manager
spec:
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.pavanzs.online"
  dnsNames:
    - pavanzs.online
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - pavanzs.online
      - "*.pavanzs.online"
#  acme:
#    config:
#      - dns01:
#          provider: route53
#        domains:
#          - "*.pavanzs.online"
#          - pavanzs.online