apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nginx-tls
  namespace: YOUR NAMESPACE
spec:
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - '*.pavanzs.online'
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - '*.pavanzs.online'