apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - "pavanzs.online"
        - "*.pavanzs.online"
      secretName: nginx-tls
  rules:
    - host: pavanzs.online
      http:
        paths:
          - path: /
            backend:
              serviceName: YOUR-SERVICE
              servicePort: 80