apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: david@zelarsoft.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - "employee.pavanzs.online"
        dns01:
          route53:
            region: us-east-1
            accessKeyID: AKIA3YT5GQXK5HCXKWVM
            secretAccessKeySecretRef:
              name: acme-route53
              key: ruBfjDnxTtsQEIia8xeEYJ27hY+7O8ucvL204UsF